name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node_version }}]
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: Run a multi-line script
      run: |
        npm install
        ng build
